const usernames = [
    "crystalwave23",
    "blazingspirit98",
    "midnightjazz77",
    "aquamarine22",
    "stellarclouds45",
    "electricpulse64",
    "wildflower31",
    "moonlitdreamer77",
    "cosmictraveler12",
    "serenadesongbird",
    "emeraldgazer88",
    "aurorabreeze17",
    "silverarrow56",
    "whisperingwillow41",
    "enigmaticdreamer",
    "lunarlullaby89",
    "sunshineglimmer",
    "twilightwanderer",
    "oceanserenade23",
    "dreamcatcher42",
    "crimsonfirefly76",
    "mysticmoonlight",
    "amethystsoul99",
    "songbirdmelody",
    "stormyseas72",
    "radiantbeams",
    "wanderingstarlight",
    "goldenember47",
    "whimsicalwanderlust",
    "velvetnightshade",
    "blazingphoenix89",
    "serenemist23",
    "whisperingechoes",
    "sapphirebreeze",
    "charmedgarden87",
    "hiddenpathways",
    "crystaldancer44",
    "lunarillusionist",
    "emberflame82",
    "melodicwhispers",
    "silentshadow56",
    "enchantedsongbird",
    "harmoniousdreams",
    "azureadventure98",
    "sparklingfirefly",
    "midnightmystic",
    "eternalserenity",
    "secretwhisperer",
    "starrynightfall",
    "mysticaljourneys",
    "whisperinggales",
    "frozenmelodies",
    "dreamsofavalon",
    "solitarywanderer",
    "celestialmelody",
    "seraphicflame88",
    "enchantedlullaby",
    "shadowedwings42",
    "glimmersoftly",
    "whispersofwinter",
    "crimsonwhisper",
    "sunsetserenade",
    "whisperingbrook",
    "radiantspirit99",
    "moonlitmeadow",
    "silvermist84",
    "aurorasparkle",
    "mistywhispers",
    "etherealwanderer",
    "sapphiremoonlight",
    "whisperinggaze",
    "luminousfirefly",
    "dreamersdelight",
    "twilightwhisper",
    "emeraldglimmer",
    "whisperingmist",
    "enchantedgarden",
    "midnightwhisper",
    "melodicwhispers",
    "crimsonwhisper",
    "goldenember47",
    "mysticaljourneys",
    "moonlitmeadow",
    "seraphicflame88",
    "silvermist84",
    "starrynightfall",
    "whispersofwinter",
    "whisperingmist",
    "aurorasparkle",
    "celestialmelody",
    "dreamersdelight",
    "emeraldglimmer",
    "etherealwanderer",
    "glimmersoftly",
    "luminousfirefly",
    "mistywhispers",
    "radiantspirit99",
    "shadowedwings42",
    "twilightwhisper",
    "whisperingbrook",
    "whisperinggaze" ,
];

const randomEmails = [
    
        "crystalwave23@example.com",
        "blazingspirit98@example.com",
        "midnightjazz77@example.com",
        "aquamarine22@example.com",
        "stellarclouds45@example.com",
        "electricpulse64@example.com",
        "wildflower31@example.com",
        "moonlitdreamer77@example.com",
        "cosmictraveler12@example.com",
        "serenadesongbird@example.com",
        "emeraldgazer88@example.com",
        "aurorabreeze17@example.com",
        "silverarrow56@example.com",
        "whisperingwillow41@example.com",
        "enigmaticdreamer@example.com",
        "lunarlullaby89@example.com",
        "sunshineglimmer@example.com",
        "twilightwanderer@example.com",
        "oceanserenade23@example.com",
        "dreamcatcher42@example.com",
        "crimsonfirefly76@example.com",
        "mysticmoonlight@example.com",
        "amethystsoul99@example.com",
        "songbirdmelody@example.com",
        "stormyseas72@example.com",
        "radiantbeams@example.com",
        "wanderingstarlight@example.com",
        "goldenember47@example.com",
        "whimsicalwanderlust@example.com",
        "velvetnightshade@example.com",
        "blazingphoenix89@example.com",
        "serenemist23@example.com",
        "whisperingechoes@example.com",
        "sapphirebreeze@example.com",
        "charmedgarden87@example.com",
        "hiddenpathways@example.com",
        "crystaldancer44@example.com",
        "lunarillusionist@example.com",
        "emberflame82@example.com",
        "melodicwhispers@example.com",
        "silentshadow56@example.com",
        "enchantedsongbird@example.com",
        "harmoniousdreams@example.com",
        "azureadventure98@example.com",
        "sparklingfirefly@example.com",
        "midnightmystic@example.com",
        "eternalserenity@example.com",
        "secretwhisperer@example.com",
        "starrynightfall@example.com",
        "mysticaljourneys@example.com",
        "whisperinggales@example.com",
        "frozenmelodies@example.com",
        "dreamsofavalon@example.com",
        "solitarywanderer@example.com",
        "celestialmelody@example.com",
        "seraphicflame88@example.com",
        "enchantedlullaby@example.com",
        "shadowedwings42@example.com",
        "glimmersoftly@example.com",
        "whispersofwinter@example.com",
        "crimsonwhisper@example.com",
        "sunsetserenade@example.com",
        "whisperingbrook@example.com",
        "radiantspirit99@example.com",
        "moonlitmeadow@example.com",
        "silvermist84@example.com",
        "aurorasparkle@example.com",
        "mistywhispers@example.com",
        "etherealwanderer@example.com",
        "sapphiremoonlight@example.com",
        "whisperinggaze@example.com",
        "luminousfirefly@example.com",
        "dreamersdelight@example.com",
        "twilightwhisper@example.com",
        "emeraldglimmer@example.com",
        "whisperingmist@example.com",
        "enchantedgarden@example.com",
        "midnightwhisper@example.com",
        "melodicwhispers@example.com",
       
      
];

const randomThoughts = [
    "The sunsets always remind me of the beauty in endings.",
    "I wonder what lies beyond the stars.",
    "Sometimes, a smile can change someone's entire day.",
    "The sound of rain is both calming and melancholic.",
    "Dreams are the windows to our hidden desires.",
    "Music has a way of speaking when words fail.",
    "In solitude, we often discover our true selves.",
    "Kindness is like a ripple in a pond, spreading far and wide.",
    "Nature has a way of healing the soul.",
    "The scent of freshly baked bread is simply irresistible.",
    "Laughter is a language understood by all.",
    "Memories are the treasure chests of our lives.",
    "A good book can transport you to another world.",
    "Happiness is found in the simplest of moments.",
    "The night sky holds countless mysteries waiting to be explored.",
    "Sometimes, all we need is a warm hug.",
    "The best lessons are learned through experience.",
    "A cup of tea can solve almost anything.",
    "Sunflowers always bring a smile to my face.",
    "Words have the power to inspire and ignite change.",
    "The sound of waves crashing on the shore is my favorite lullaby.",
    "Challenges are opportunities for growth.",
    "Stars are like whispers from distant galaxies.",
    "Love is the universal language that binds us all.",
    "Mistakes are stepping stones on the path to success.",
    "A single act of kindness can change the world.",
    "Imagination has no limits or boundaries.",
    "Rainbows are a reminder of hope after the storm.",
    "The smell of fresh-cut grass reminds me of childhood summers.",
    "A walk in nature can clear the clutter in our minds.",
    "Every ending is a new beginning in disguise.",
    "The best way to predict the future is to create it.",
    "Silence speaks volumes when words are inadequate.",
    "Art has the power to move hearts and stir emotions.",
    "A gentle breeze can carry away our worries.",
    "The sweetest moments are often the simplest ones.",
    "We are all interconnected threads in the tapestry of life.",
    "Time is a precious gift, use it wisely.",
    "The moon is a faithful companion in the darkest of nights.",
    "Success is not measured by material possessions, but by inner fulfillment.",
    "A warm fireplace and good company make for a perfect evening.",
    "The sound of children's laughter is pure magic.",
    "The world needs more dreamers and believers.",
    "The scent of a blooming flower can turn a bad day around.",
    "Every ending is an invitation for a new beginning.",
    "A smile is the most beautiful curve on a person's face.",
    "Courage is not the absence of fear, but the triumph over it.",
    "Dancing in the rain is liberating and exhilarating.",
    "Life is a journey, enjoy the scenery along the way.",
    "True beauty shines from within.",
    "The sound of a loved one's voice can instantly bring comfort.",
    "Every person we meet has a story worth listening to.",
    "Worrying does not take away tomorrow's troubles, it takes away today's peace.",
    "A soft pillow and a cozy blanket make for a perfect night's sleep.",
    "The best adventures are the ones we least expect.",
    "The taste of chocolate can make any day better.",
    "The world needs more love and compassion.",
    "Forgiveness sets us free from the chains of the past.",
    "The smell of rain on a hot day",
  

];

const randomReactions = [
    "So true!",
    "I can relate.",
    "Wow, that's deep.",
    "Exactly!",
    "I never thought of it that way.",
    "That's beautiful.",
    "Oh, I love that!",
    "So inspiring.",
    "Absolutely!",
    "Aha, I get it now.",
    "Incredible!",
    "Yes, yes, yes!",
    "Oh, how true that is.",
    "Well said!",
    "That resonates with me.",
    "I couldn't agree more.",
    "Oh, the nostalgia!",
    "So profound.",
    "That's a great perspective.",
    "I needed to hear that.",
    "It's like you read my mind.",
    "That's so powerful.",
    "I'm speechless.",
    "Couldn't have said it better.",
    "That's spot on!",
    "This speaks to me.",
    "Oh, I love this thought.",
    "Absolutely mind-blowing!",
    "That's pure wisdom.",
    "Such a simple truth.",
    "Incredible insight.",
    "I'm in awe.",
    "Oh, the beauty in that.",
    "So beautifully expressed.",
    "This made my day.",
    "Brilliant!",
    "I'm touched.",
    "Oh, I needed this reminder.",
    "So refreshing to hear.",
    "That's so profound.",
    "You've captured it perfectly.",
    "This gives me hope.",
    "Wow, just wow.",
    "I'm inspired.",
    "That's exactly what I needed.",
    "Oh, how true!",
    "I'm moved by this thought.",
    "I'm in agreement.",
    "This is pure gold.",
    "That's so relatable.",
    "I'm smiling ear to ear.",
    "Oh, how beautiful.",
    "You've nailed it.",
    "This made me pause and reflect.",
    "I'm impressed.",
    "So thought-provoking.",
    "This is everything.",
    "Oh, the truth in those words.",
    "I'm grateful for this insight.",
    "Absolutely mind-opening.",
    "This makes my heart happy.",
    "You've got me thinking.",
    "Oh, the simplicity of it.",
    "I'm captivated by this thought.",
    "So, so true.",
    "This is pure brilliance.",
    "I couldn't agree more!",
    "Oh, this hits home.",
    "You've got a way with words.",
    "This is a game-changer.",
    "I'm in love with this thought.",
    "So beautifully stated.",
    "This resonates deeply.",
    "Oh, how I needed this.",
    "I'm applauding your insight.",
    "This is pure magic.",
    "I'm embracing this thought.",
    "Oh, I'm smiling now.",
    "This speaks volumes.",
    "I'm sharing this with others.",
    "This deserves a standing ovation.",
    "Oh, the power of these words.",
    "I'm touched to the core.",
    "This is life-changing.",
    "I'm bookmarking this thought.",
    "Oh, this makes my heart sing.",
    "This is a revelation.",
    "I'm nodding in agreement.",
    "So beautifully articulated.",
    "This is soul-stirring.",
    "Oh, the truth in this."  
  ]

  
  const users = [];

//   get a random item given any array

const getRandomArrItem = (arr) => arr[Math.floor(Math.random() * arr.length)];

const getRandomUser = () =>
`${getRandomArrItem(usernames)}`;

const getRandomEmail = (int) => {
    if (int === 1) {
        return getRandomArrItem(randomEmails);
    }
    const results = [];
    for (let i = 0; i < int; i++) {
        results.push({
          email: getRandomArrItem(randomEmails),
          username: getRandomUser(),
        });
      }
      return results;
    };

const getRandomThought = (int) => {
        if (int === 1) {
            return getRandomArrItem(randomThoughts);
        }
        const results = [];
        for (let i = 0; i < int; i++) {
            results.push({
              thoughts: getRandomArrItem(randomThoughts),
              createdAt: Date.now,
              reactions: [...getReactions(3)],

            });
          }
          return results;};

const getReactions = (int) => {
            if (int === 1) {
                return getRandomArrItem(randomReactions);
            }
            const results = [];
            for (let i = 0; i < int; i++) {
                results.push({
                  reactionBody: getRandomArrItem(randomReactions),
                  createdAt: Date.now,
                  reactions: [...getReactions(3)],
                  username: getRandomUser(),
    
                });
              }
              return results;
            };
    

  